/**
 * Step-up MFA primitives (TOTP).
 *
 * SCOPE NOTE (slice 1 stub): this module exposes the wire shapes and
 * verification logic for TOTP-based step-up MFA, but it does NOT yet
 * persist secrets. `enrollMfa` returns a fresh secret + provisioning URI
 * the client is expected to keep until `verifyMfa` is called. Slice 2
 * will add a `mfa_secret` column on the user table, encrypt the secret at
 * rest with KMS, and gate enrolment behind a re-authentication.
 *
 * Library: `otpauth` v9.x. Pure-JS, dependency-free, RFC 6238 / 4226
 * compliant. Picked over `speakeasy` because the latter is unmaintained
 * (last release 2017) and pulls in deprecated transitive deps.
 */
import { Secret, TOTP } from "otpauth";

/**
 * TOTP issuer label that shows up in the user's authenticator app. Hard-
 * coded to "Panakoes" for the v0.1 MVP; future per-tenant white-labelling
 * can override via env without changing the contract.
 */
export const MFA_ISSUER = "Panakoes";

/** Standard TOTP parameters: 6-digit code, 30-second window, SHA-1. */
export const MFA_DIGITS = 6;
export const MFA_PERIOD_SECONDS = 30;
export const MFA_ALGORITHM = "SHA1" as const;

/**
 * Allowed verification window in 30-second steps either side of the
 * current step. `1` means "accept the previous, current, or next code"
 * which absorbs ~30s of clock skew between client and server.
 */
export const MFA_VERIFY_WINDOW = 1;

export interface EnrollmentOffer {
  /** Base32-encoded TOTP secret. The client must persist this. */
  secret_key: string;
  /** `otpauth://totp/...` URI suitable for rendering as a QR code. */
  qr_code_uri: string;
}

export interface EnrollmentInput {
  /** Account label used in the otpauth URI (typically the user's email). */
  accountLabel: string;
  /** Optional issuer override; defaults to `MFA_ISSUER`. */
  issuer?: string;
}

/**
 * Generate a fresh TOTP secret + provisioning URI for the supplied
 * account label. The secret is generated by `otpauth` via the platform
 * Web Crypto RNG; we never seed it ourselves.
 *
 * Slice-2 wiring point: persist the secret (encrypted) on the user row
 * and only return it to the client once at enrolment time.
 */
export function enrollMfa(input: EnrollmentInput): EnrollmentOffer {
  const issuer = input.issuer ?? MFA_ISSUER;
  const secret = new Secret({ size: 20 });
  const totp = new TOTP({
    issuer,
    label: input.accountLabel,
    algorithm: MFA_ALGORITHM,
    digits: MFA_DIGITS,
    period: MFA_PERIOD_SECONDS,
    secret,
  });
  return {
    secret_key: secret.base32,
    qr_code_uri: totp.toString(),
  };
}

export type MfaVerifyResult =
  | { ok: true }
  | { ok: false; reason: "invalid_code" | "malformed_code" | "malformed_secret" };

/**
 * Validate a 6-digit TOTP code against a base32-encoded secret. Returns a
 * tagged-union result; never throws. `malformed_code` covers the shape
 * check (must be 6 digits); `malformed_secret` covers a base32 parse
 * failure on the persisted secret; `invalid_code` covers a real auth
 * failure (wrong code or out-of-window).
 */
export function verifyMfaCode(code: string, base32Secret: string): MfaVerifyResult {
  if (!/^\d{6}$/.test(code)) {
    return { ok: false, reason: "malformed_code" };
  }
  let secret: Secret;
  try {
    secret = Secret.fromBase32(base32Secret);
  } catch {
    return { ok: false, reason: "malformed_secret" };
  }
  const totp = new TOTP({
    issuer: MFA_ISSUER,
    algorithm: MFA_ALGORITHM,
    digits: MFA_DIGITS,
    period: MFA_PERIOD_SECONDS,
    secret,
  });
  const delta = totp.validate({ token: code, window: MFA_VERIFY_WINDOW });
  if (delta === null) {
    return { ok: false, reason: "invalid_code" };
  }
  return { ok: true };
}
