// `/ingestion/[id]` is a dynamic, per-user, polling-driven page. It cannot
// be pre-rendered at build time because the ingestion id is generated by
// `ingestion-api` at runtime. SvelteKit's adapter-static fails the build
// otherwise (`route /ingestion/[id] was marked prerenderable but not found
// while crawling`). Marking it client-rendered keeps the static build path
// happy and matches how every other authenticated route in the SPA works.

export const prerender = false;
export const ssr = false;
