"""Validator tests for the `AuditEvent` model."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta, timezone

import pytest
from pydantic import ValidationError

from panakoes_audit.event import AuditEvent

VALID_KWARGS: dict[str, object] = {
    "actor_id": "user_abc",
    "actor_type": "user",
    "action": "transcript.created",
    "resource_type": "transcript",
    "resource_id": "trnscr_xyz",
    "source_service": "ingestion",
}


@pytest.mark.unit
def test_event_with_minimum_fields_construct_successfully() -> None:
    """Default factories fill timestamp + request_id when callers omit them."""
    event = AuditEvent(**VALID_KWARGS)  # type: ignore[arg-type]
    assert event.actor_id == "user_abc"
    assert event.actor_type == "user"
    assert event.action == "transcript.created"
    assert event.resource_type == "transcript"
    assert event.resource_id == "trnscr_xyz"
    assert event.source_service == "ingestion"
    assert event.request_id  # auto-generated
    assert event.timestamp.tzinfo is not None
    assert event.timestamp.utcoffset() == UTC.utcoffset(event.timestamp)
    assert event.details == {}
    assert event.source_ip is None


@pytest.mark.unit
def test_request_id_autogenerated_is_unique() -> None:
    """Two events constructed back-to-back receive different `request_id` values."""
    event1 = AuditEvent(**VALID_KWARGS)  # type: ignore[arg-type]
    event2 = AuditEvent(**VALID_KWARGS)  # type: ignore[arg-type]
    assert event1.request_id != event2.request_id


@pytest.mark.unit
@pytest.mark.parametrize(
    "action",
    [
        "transcript.created",
        "user.signed_in",
        "billing.invoice_paid",
        "summary.generated",
    ],
)
def test_action_accepts_valid_dot_pattern(action: str) -> None:
    """Domain.verb pattern with snake_case segments is accepted."""
    event = AuditEvent(**{**VALID_KWARGS, "action": action})  # type: ignore[arg-type]
    assert event.action == action


@pytest.mark.unit
@pytest.mark.parametrize(
    "action",
    [
        "",
        "no_dot",
        ".missing_prefix",
        "missing_suffix.",
        "Capitalized.action",
        "two.dots.here",
        "1starts_with_digit.action",
        "domain.With_Caps",
        "domain. ws",
    ],
)
def test_action_rejects_invalid_patterns(action: str) -> None:
    """Anything outside the strict regex raises a `ValidationError`."""
    with pytest.raises(ValidationError):
        AuditEvent(**{**VALID_KWARGS, "action": action})  # type: ignore[arg-type]


@pytest.mark.unit
@pytest.mark.parametrize("field", ["actor_id", "resource_type", "resource_id", "source_service"])
def test_required_string_fields_reject_empty(field: str) -> None:
    """Empty strings on required fields surface as validation errors."""
    bad_kwargs = {**VALID_KWARGS, field: ""}
    with pytest.raises(ValidationError):
        AuditEvent(**bad_kwargs)  # type: ignore[arg-type]


@pytest.mark.unit
def test_actor_type_rejects_unknown_value() -> None:
    """Only the documented actor_type literals are accepted."""
    with pytest.raises(ValidationError):
        AuditEvent(**{**VALID_KWARGS, "actor_type": "robot"})  # type: ignore[arg-type]


@pytest.mark.unit
def test_actor_type_accepts_all_documented_values() -> None:
    """Every documented actor_type literal is accepted."""
    for value in ("user", "service", "system", "anonymous"):
        event = AuditEvent(**{**VALID_KWARGS, "actor_type": value})  # type: ignore[arg-type]
        assert event.actor_type == value


@pytest.mark.unit
def test_naive_timestamp_is_rejected() -> None:
    """A timestamp without a timezone is rejected."""
    naive = datetime(2026, 5, 7, 12, 0, 0)
    with pytest.raises(ValidationError):
        AuditEvent(**{**VALID_KWARGS, "timestamp": naive})  # type: ignore[arg-type]


@pytest.mark.unit
def test_non_utc_timestamp_is_rejected() -> None:
    """A timestamp in a non-UTC zone is rejected."""
    eastern = timezone(timedelta(hours=-5))
    aware = datetime(2026, 5, 7, 12, 0, 0, tzinfo=eastern)
    with pytest.raises(ValidationError):
        AuditEvent(**{**VALID_KWARGS, "timestamp": aware})  # type: ignore[arg-type]


@pytest.mark.unit
def test_future_timestamp_is_rejected() -> None:
    """A timestamp far enough in the future to exceed clock-skew tolerance fails."""
    future = datetime.now(UTC) + timedelta(minutes=5)
    with pytest.raises(ValidationError):
        AuditEvent(**{**VALID_KWARGS, "timestamp": future})  # type: ignore[arg-type]


@pytest.mark.unit
def test_explicit_request_id_is_preserved() -> None:
    """A caller-supplied `request_id` is not overwritten by the default factory."""
    event = AuditEvent(**{**VALID_KWARGS, "request_id": "req_explicit"})  # type: ignore[arg-type]
    assert event.request_id == "req_explicit"


@pytest.mark.unit
def test_empty_request_id_is_rejected() -> None:
    """Caller cannot pass an empty `request_id` to bypass uniqueness."""
    with pytest.raises(ValidationError):
        AuditEvent(**{**VALID_KWARGS, "request_id": ""})  # type: ignore[arg-type]


@pytest.mark.unit
def test_extra_fields_are_rejected() -> None:
    """Unknown fields raise `ValidationError` (extra='forbid')."""
    with pytest.raises(ValidationError):
        AuditEvent(**{**VALID_KWARGS, "unknown": "value"})  # type: ignore[arg-type]


@pytest.mark.unit
def test_details_round_trip_through_json() -> None:
    """`details` dict survives JSON round-tripping."""
    event = AuditEvent(
        **{**VALID_KWARGS, "details": {"audio_duration_seconds": 245, "format": "wav"}}  # type: ignore[arg-type]
    )
    raw = event.model_dump_json()
    assert "audio_duration_seconds" in raw
    assert "245" in raw
