#!/usr/bin/env bash
#
# design-review.sh -- mechanical setup for the design-review cycle (WORKFLOW.md 5.6).
#
# The orchestrator dispatches the actual review agents (Claude-only). This script
# handles the bookkeeping that's the same every time:
#   1. Validate the design doc exists and is on a branch.
#   2. Create a sibling worktree off origin/main (architect) or off the design
#      branch's tip (adversarial).
#   3. Fill the right template (architect or adversarial) with concrete paths
#      and write it as AGENT_BRIEF.md inside the worktree.
#   4. Print the exact next-step instructions for the orchestrator.
#
# Usage:
#   scripts/design-review.sh architect   <path/to/design.md>
#   scripts/design-review.sh adversarial <path/to/design.md>
#
# Both stages use the same `<design-doc-path>` argument; the slug is derived from
# its basename. The script writes nothing to stdout that the orchestrator needs to
# parse mechanically; the printout is for humans (which is the orchestrator).

set -euo pipefail

usage() {
    cat >&2 <<'EOF'
usage: design-review.sh <stage> <design-doc-path>

stages:
  architect    Stage 1: set up worktree + architect-reviewer brief.
               Worktree based on origin/main.
  adversarial  Stage 3: set up worktree + adversarial-reviewer brief.
               Worktree based on the design doc's current branch tip.

The design doc path is relative to the repo root (e.g. docs/design/foo.md).
EOF
    exit 2
}

[[ $# -eq 2 ]] || usage
STAGE="$1"
DESIGN_DOC="$2"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

[[ -f "$DESIGN_DOC" ]] || { echo "error: design doc not found at $DESIGN_DOC" >&2; exit 3; }

SLUG="$(basename "$DESIGN_DOC" .md | tr '[:upper:]_' '[:lower:]-' | sed 's/[^a-z0-9-]/-/g')"
DESIGN_BRANCH="$(git log -1 --format=%H -- "$DESIGN_DOC" 2>/dev/null || true)"

case "$STAGE" in
    architect)
        TEMPLATE="$REPO_ROOT/docs/templates/agent-brief-architect-reviewer.md"
        WORKTREE_NAME="panakoes-architect-review-${SLUG}"
        BRANCH="reviews/architect-of-${SLUG}"
        BASE="origin/main"
        ;;
    adversarial)
        TEMPLATE="$REPO_ROOT/docs/templates/agent-brief-adversarial-reviewer.md"
        WORKTREE_NAME="panakoes-adversarial-review-${SLUG}"
        BRANCH="reviews/adversarial-of-${SLUG}"
        # Adversarial reviews the design AFTER architect updates land. Default
        # base = the current tip of whatever branch the design doc lives on.
        # The orchestrator can override BASE via env if a more specific commit
        # is needed.
        BASE="${ADVERSARIAL_BASE:-origin/main}"
        ;;
    *)
        usage
        ;;
esac

[[ -f "$TEMPLATE" ]] || { echo "error: template not found at $TEMPLATE" >&2; exit 4; }

WORKTREE_PATH="$REPO_ROOT/../$WORKTREE_NAME"

if git worktree list --porcelain | grep -q "^worktree $WORKTREE_PATH$"; then
    echo "note: worktree already exists at $WORKTREE_PATH; will reuse" >&2
else
    echo "creating worktree: $WORKTREE_PATH (branch $BRANCH, base $BASE)" >&2
    git fetch origin --quiet
    git worktree add "$WORKTREE_PATH" -b "$BRANCH" "$BASE" >/dev/null
fi

BRIEF_PATH="$WORKTREE_PATH/AGENT_BRIEF.md"

# Fill the template's placeholders with concrete values. The templates use
# <<DESIGN_DOC_PATH>>, <<WORKTREE_PATH>>, <<SLUG>>. We rewrite all of them.
sed \
    -e "s|<<DESIGN_DOC_PATH>>|$DESIGN_DOC|g" \
    -e "s|<<WORKTREE_PATH>>|$WORKTREE_PATH|g" \
    -e "s|<<SLUG>>|$SLUG|g" \
    "$TEMPLATE" > "$BRIEF_PATH"

# Add a small front-matter note for the agent
{
    echo "# THIS IS THE FILLED-IN AGENT BRIEF FOR THIS REVIEW"
    echo ""
    echo "Generated by scripts/design-review.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "Stage: $STAGE | Design doc: $DESIGN_DOC | Worktree: $WORKTREE_PATH"
    echo ""
    echo "Read this file completely. The agent's task and acceptance criteria"
    echo "are below."
    echo ""
    echo "---"
    echo ""
    cat "$BRIEF_PATH"
} > "$BRIEF_PATH.tmp" && mv "$BRIEF_PATH.tmp" "$BRIEF_PATH"

cat <<EOF

design-review.sh: $STAGE stage setup complete.

  worktree:    $WORKTREE_PATH
  branch:      $BRANCH
  base:        $BASE
  brief:       $BRIEF_PATH
  design doc:  $DESIGN_DOC

Next step (orchestrator action):

  Dispatch the $STAGE-reviewer agent in background mode. Tell the agent:
  "Your brief is at $BRIEF_PATH. Read it completely before any action."

  See WORKFLOW.md section 5.6 (Design Review Cycle) for the Phil-gate moderation
  pattern after the agent returns.

EOF
