"""Shape tests for `scripts/seed-cost-api-dynamodb.py`.

These tests cover the pure data-generation surface of the seed script
(no boto3 calls). They guard against drift between the script's synthetic
output and the cost-api response models that consume the seeded rows:

- Each generated by-service cache payload must validate against
  `CostBreakdown`.
- Each generated by-tenant cache payload must validate against
  `TenantCostBreakdown`.
- Each anomaly payload must validate against `CostAnomaly`.
- Tenant rollup totals must reconcile (sum of daily rows == aggregated
  payload total for the same window).
- The script must emit 30 days * N services rows when given days=30.
- Anomalies carry plausible deviation values (sanity check on the
  synthetic spike math).

How this runs: the test file lives at the repo root under
`tests/scripts/`. It is exercised via `uv run pytest ../../tests/scripts`
from `services/cost-api/`, which is the env that already has boto3 +
pydantic available. The cost-api Makefile-driven pytest discovers it via
`testpaths` only when invoked from inside cost-api with an explicit
path; this is intentionally narrow because the test imports cost-api
models directly.
"""

from __future__ import annotations

import importlib.util
import pathlib
import sys
from datetime import UTC, date, datetime, timedelta

import pytest

# The cost-api models are the contract under test. If pydantic / cost-api
# is not importable in this environment we skip cleanly rather than
# pretending to pass.
pytest.importorskip("pydantic")
try:
    from panakoes_cost_api.models import (
        CostAnomaly,
        CostBreakdown,
        TenantCostBreakdown,
    )
except ImportError:  # pragma: no cover - guard for non-cost-api envs.
    pytest.skip("panakoes-cost-api not installed in this environment",
                allow_module_level=True)


# Load the seed script by file path because the filename has a hyphen.
_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
_SCRIPT_PATH = _REPO_ROOT / "scripts" / "seed-cost-api-dynamodb.py"


def _load_seed_module():  # type: ignore[no-untyped-def]
    spec = importlib.util.spec_from_file_location("seed_cost_api", _SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["seed_cost_api"] = module
    spec.loader.exec_module(module)
    return module


seed = _load_seed_module()


# ---------------------------------------------------------------------------
# Daily service generation
# ---------------------------------------------------------------------------


def test_daily_service_rows_count() -> None:
    """30 days * len(AWS_SERVICES) rows when days=30."""
    today = date(2026, 5, 11)
    rows = seed.generate_daily_service_costs(today, days=30)
    assert len(rows) == 30 * len(seed.AWS_SERVICES)


def test_daily_service_rows_one_per_service_per_day() -> None:
    today = date(2026, 5, 11)
    rows = seed.generate_daily_service_costs(today, days=30)
    by_day: dict[date, set[str]] = {}
    for r in rows:
        by_day.setdefault(r.day, set()).add(r.service)
    expected_services = {s for s, _ in seed.AWS_SERVICES}
    for day, services in by_day.items():
        assert services == expected_services, f"missing services on {day}"


def test_anomaly_spike_present_in_synthetic_series() -> None:
    """Bedrock day-3 should be >= 2x the median of the prior 14 days."""
    today = date(2026, 5, 11)
    rows = seed.generate_daily_service_costs(today, days=30)
    bedrock = sorted(
        [r for r in rows if r.service == "Amazon Bedrock"], key=lambda r: r.day
    )
    spike_day = today - timedelta(days=3)
    spike = next(r for r in bedrock if r.day == spike_day).cost_cents
    # Trailing 14-day median excluding the spike day itself.
    trailing = [r.cost_cents for r in bedrock if r.day < spike_day][-14:]
    median = sorted(trailing)[len(trailing) // 2]
    assert spike >= median * 2


# ---------------------------------------------------------------------------
# CostBreakdown shape
# ---------------------------------------------------------------------------


def test_cost_breakdown_payload_validates_against_pydantic_model() -> None:
    today = date(2026, 5, 11)
    rows = seed.generate_daily_service_costs(today, days=30)
    for window in seed.DEFAULT_WINDOWS_DAYS:
        payload = seed.build_cost_breakdown_payload(
            today - timedelta(days=window), today, rows
        )
        model = CostBreakdown.model_validate(payload)
        assert model.total_cents == sum(s.cost_cents for s in model.services)
        # Percent-of-total must reconcile to 100 within 2 dp rounding.
        pct_sum = sum(s.percent_of_total for s in model.services)
        if model.total_cents > 0:
            assert abs(pct_sum - 100.0) < 1.0


# ---------------------------------------------------------------------------
# TenantCostBreakdown shape and reconciliation
# ---------------------------------------------------------------------------


def test_tenant_breakdown_validates_and_reconciles() -> None:
    today = date(2026, 5, 11)
    rollup_rows = seed.generate_tenant_daily_rows(today, days=30)
    for window in seed.DEFAULT_WINDOWS_DAYS:
        from_date = today - timedelta(days=window)
        payload = seed.build_tenant_breakdown_payload(from_date, today, rollup_rows)
        model = TenantCostBreakdown.model_validate(payload)
        # Reconcile: sum of per-tenant totals equals total_cents.
        assert sum(t.cost_cents for t in model.tenants) == model.total_cents
        # Reconcile: that total equals the sum of daily rows in window.
        window_total = sum(
            cents for _, day, cents in rollup_rows if from_date <= day < today
        )
        assert model.total_cents == window_total


def test_tenant_rollup_one_row_per_tenant_per_day() -> None:
    today = date(2026, 5, 11)
    rows = seed.generate_tenant_daily_rows(today, days=30)
    assert len(rows) == 30 * len(seed.TENANTS)


# ---------------------------------------------------------------------------
# CostAnomaly shape
# ---------------------------------------------------------------------------


def test_anomaly_payloads_validate_against_pydantic_model() -> None:
    today = date(2026, 5, 11)
    for payload in seed.build_anomaly_payloads(today):
        model = CostAnomaly.model_validate(payload)
        # Status-ish fields: must be one of the recognized detector names
        # the dashboard knows how to render.
        assert model.detector in {"ce-cost-spike", "ce-rate-of-change"}
        assert model.observed_cost_cents > model.expected_cost_cents
        assert model.deviation_pct > 0
        assert model.suppressed is False


def test_anomaly_signatures_are_stable_across_calls() -> None:
    """Re-running the script must overwrite the same alert-state rows,
    not fan-out duplicates. Signatures are the dedup key, so they must
    be deterministic for the same `today`."""
    today = date(2026, 5, 11)
    a = [p["signature"] for p in seed.build_anomaly_payloads(today)]
    b = [p["signature"] for p in seed.build_anomaly_payloads(today)]
    assert a == b


# ---------------------------------------------------------------------------
# Cache key parity with cost-api models
# ---------------------------------------------------------------------------


def test_cache_key_matches_cost_api_models() -> None:
    """The script's `_cache_key_string` must agree with `CacheKey.to_string()`
    in cost-api, otherwise the seeded rows land at the wrong key and the
    route never sees them."""
    from panakoes_cost_api.models import CacheKey

    from_date = date(2026, 4, 11)
    to_date = date(2026, 5, 11)
    expected = CacheKey(
        query_kind="by-service", from_date=from_date, to_date=to_date
    ).to_string()
    actual = seed._cache_key_string("by-service", from_date, to_date)
    assert actual == expected


# ---------------------------------------------------------------------------
# CLI argument parsing
# ---------------------------------------------------------------------------


def test_parse_args_defaults() -> None:
    ns = seed._parse_args([])
    assert ns.dry_run is False
    assert ns.force is False
    assert ns.limit is None
    assert ns.days == 30


def test_parse_args_dry_run_and_limit() -> None:
    ns = seed._parse_args(["--dry-run", "--limit", "3", "--days", "7"])
    assert ns.dry_run is True
    assert ns.limit == 3
    assert ns.days == 7


# ---------------------------------------------------------------------------
# JSON log formatting
# ---------------------------------------------------------------------------


def test_logger_emits_json() -> None:
    log = seed._build_logger()
    # Build a record and run it through the formatter directly.
    fmt = log.handlers[0].formatter
    assert fmt is not None
    import logging as _logging
    record = _logging.LogRecord(
        name="seed_cost_api", level=_logging.INFO,
        pathname=__file__, lineno=1, msg="hello",
        args=(), exc_info=None,
    )
    record.foo = "bar"
    rendered = fmt.format(record)
    import json as _json
    parsed = _json.loads(rendered)
    assert parsed["msg"] == "hello"
    assert parsed["foo"] == "bar"
    assert parsed["level"] == "info"


# unused-import guard for IDE
_ = (datetime, UTC)
